package model;
// Generated 2020/7/22 �U�� 03:11:40 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Student generated by hbm2java
 */
@Entity
@Table (name = "student")
public class Student  implements java.io.Serializable {


     private String studentId;
     private String name;
     private String address;

    public Student() {
    }

    public Student(String studentId, String name, String address) {
       this.studentId = studentId;
       this.name = name;
       this.address = address;
    }
   
    @Id
    @Column (name = "studentID")
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
}


